### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by miura** [LauLauThom/RoiGroupTable#1]
Hi @LauLauThom 

It seems that there is more information in the latest state. 
Don't hesitate to make a new release and update the Zenodo repo. We will accept again the new version as the NEUBAIS community contribution.

**Comment by LauLauThom** [comment]
Hello Kota,
indeed I updated the plugin and readme with the Zenodo citation, which I could not get before actually posting a first release..
Otherwise the code has not changed, so not sure if it's really necessary to post a new release since it's not really a new version of the plugin.

**Comment by miura** [comment]
OK!
